function file_type = check_inputs(...
    project_directory,...
    data_directory,...
    database_name,...
    file_type,...
    data_structure,...
    start_date,...
    end_date,...
    channel_list,...
    coordinate_file...
    )

% Check project directory exists
assert( isfolder( project_directory ) == 1,...
    'Project directory does not exist. Check directory PATH!')

% Check data directory exists
assert( isfolder( data_directory ) == 1,...
    'Data directory does not exist. Check directory PATH!')

% Check the station coordinate file exists
assert( isfile( coordinate_file ) == 1,...
    'Station coordinate file does not exist. Check file PATH!')

% Check data format
assert(...
    strcmp(file_type,'sac')==1 ||...
    strcmp(file_type,'miniseed')==1 ||...
    strcmp(file_type,'seed')==1,...
    'Data type not recognized. Must be ''sac'', ''seed'' or ''miniseed''.');

if strcmp(file_type,'miniseed')
    file_type = 'seed'; % get correct name for waveform()
end

% Check data organization structure
assert(...
    strcmp(data_structure,'BUD')==1 ||...
    strcmp(data_structure,'DMT')==1 ||...
    strcmp(data_structure,'ANT')==1 ||...
    strcmp(data_structure,'SDS')==1 ,...
    'Data structure not recognized. Must be ''BUD'' or ''DMT'' or ''ANT'' or ''SDS''.');

end % check_inputs